#!/usr/bin/expect -f

if { $argc < 1 } {
	send_user "usage: kernel-dump vmcore.img\n"
	exit
}
set out_file [lindex $argv 0]

spawn telnet localhost 4444
send "{ \"execute\": \"qmp_capabilities\" }\r"
expect "{\"return\": {}}"
send "{\"execute\":\"dump-guest-memory\",\"arguments\":{\"paging\":false,\"protocol\":\"file:$out_file\"}}\r"
expect "{\"return\": {}}"
